version: '3.9'
services:
  php:
    container_name: dinamk
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: "php -S 0.0.0.0:80"
    depends_on:
      - mysqldb
    links:
      - mysqldb   

  mysqldb:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=dinamk
      - MYSQL_ROOT_PASSWORD=root 
    volumes:    
      - ./mysqldb:/var/lib/mysql
